/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as MainImport } from './routes/_main'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as MainIndexImport } from './routes/_main.index'
import { Route as DashboardAccountImport } from './routes/_dashboard.account'
import { Route as DashboardRecipeNewImport } from './routes/_dashboard.recipe.new'
import { Route as DashboardRecipeRecipeIdImport } from './routes/_dashboard.recipe.$recipeId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const DashboardAccountRoute = DashboardAccountImport.update({
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRecipeNewRoute = DashboardRecipeNewImport.update({
  path: '/recipe/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRecipeRecipeIdRoute = DashboardRecipeRecipeIdImport.update({
  path: '/recipe/$recipeId',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/account': {
      preLoaderRoute: typeof DashboardAccountImport
      parentRoute: typeof DashboardImport
    }
    '/_main/': {
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_dashboard/recipe/$recipeId': {
      preLoaderRoute: typeof DashboardRecipeRecipeIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/recipe/new': {
      preLoaderRoute: typeof DashboardRecipeNewImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardAccountRoute,
    DashboardRecipeRecipeIdRoute,
    DashboardRecipeNewRoute,
  ]),
  MainRoute.addChildren([MainIndexRoute]),
  LoginRoute,
])

/* prettier-ignore-end */
