/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as MainImport } from './routes/_main'
import { Route as MainIndexImport } from './routes/_main.index'
import { Route as AccountDashboardImport } from './routes/account/_dashboard'
import { Route as AccountDashboardIndexImport } from './routes/account/_dashboard.index'
import { Route as AccountDashboardSavedImport } from './routes/account/_dashboard.saved'
import { Route as AccountDashboardRecipeNewImport } from './routes/account/_dashboard.recipe.new'
import { Route as AccountDashboardRecipeEditRecipeIdImport } from './routes/account/_dashboard.recipe.edit.$recipeId'

// Create Virtual Routes

const AccountImport = createFileRoute('/account')()

// Create/Update Routes

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AccountDashboardRoute = AccountDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AccountRoute,
} as any)

const AccountDashboardIndexRoute = AccountDashboardIndexImport.update({
  path: '/',
  getParentRoute: () => AccountDashboardRoute,
} as any)

const AccountDashboardSavedRoute = AccountDashboardSavedImport.update({
  path: '/saved',
  getParentRoute: () => AccountDashboardRoute,
} as any)

const AccountDashboardRecipeNewRoute = AccountDashboardRecipeNewImport.update({
  path: '/recipe/new',
  getParentRoute: () => AccountDashboardRoute,
} as any)

const AccountDashboardRecipeEditRecipeIdRoute =
  AccountDashboardRecipeEditRecipeIdImport.update({
    path: '/recipe/edit/$recipeId',
    getParentRoute: () => AccountDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/account/_dashboard': {
      preLoaderRoute: typeof AccountDashboardImport
      parentRoute: typeof AccountRoute
    }
    '/_main/': {
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/account/_dashboard/saved': {
      preLoaderRoute: typeof AccountDashboardSavedImport
      parentRoute: typeof AccountDashboardImport
    }
    '/account/_dashboard/': {
      preLoaderRoute: typeof AccountDashboardIndexImport
      parentRoute: typeof AccountDashboardImport
    }
    '/account/_dashboard/recipe/new': {
      preLoaderRoute: typeof AccountDashboardRecipeNewImport
      parentRoute: typeof AccountDashboardImport
    }
    '/account/_dashboard/recipe/edit/$recipeId': {
      preLoaderRoute: typeof AccountDashboardRecipeEditRecipeIdImport
      parentRoute: typeof AccountDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainRoute.addChildren([MainIndexRoute]),
  LoginRoute,
  AccountRoute.addChildren([
    AccountDashboardRoute.addChildren([
      AccountDashboardSavedRoute,
      AccountDashboardIndexRoute,
      AccountDashboardRecipeNewRoute,
      AccountDashboardRecipeEditRecipeIdRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
